services:
  rproxy:
    image: rproxy:latest
    container_name: rproxy_container
    build:
      context: ${PWD}
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - auth
      - frontend
      # - backend
  database:
    image: database:latest
    container_name: database_container
    build:
      context: ${PWD}
      dockerfile: ./database/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      # MYSQL_USER: "user"
      # MYSQL_PASSWORD: "user"
      MYSQL_DATABASE: "gamePlatform"
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u user", "-p user"]
      interval: 10s
      retries: 5
      timeout: 5s
    ports:
      - "3306:3306"
    # volumes:
    #   - ./database/data:/var/lib/mysql
  auth:
    image: auth:latest
    container_name: auth_container
    build:
      context: ${PWD}
      dockerfile: ./auth/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    # ports:
    #   - 3000:3000
  frontend:
    image: frontend:latest
    container_name: frontend_container
    build:
      context: ${PWD}
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - auth

  backend:
    image: backend:latest
    container_name: backend_container
    build:
      context: ${PWD}
      dockerfile: ./backend/Dockerfile
    depends_on:
      database:
        condition: service_healthy


    # ports:
    #   - 5173:5173
#   game_backend:
#   game_frontend:
#
