const PORT = 3000;
const MYSQL_HOST = "localhost";
const MYSQL_PORT = 3306;
const MYSQL_DATABASE = "gamePlatform";
const MYSQL_DIALECT = "mysql";
const MYSQL_USERNAME = "root";
const MYSQL_PASSWORD = "root";
const JWT_PRIVATEKEY = "privateKey";
const JWT_EXPIRATIONTIME = "1h";
const BCRYPT_SALTROUNDS = 10;

export {
  PORT,
  MYSQL_HOST,
  MYSQL_PORT,
  MYSQL_DATABASE,
  MYSQL_DIALECT,
  MYSQL_USERNAME,
  MYSQL_PASSWORD,
  JWT_PRIVATEKEY,
  JWT_EXPIRATIONTIME,
  BCRYPT_SALTROUNDS,
};
