const DOCKER = false
const AXIOS_AUTH_CLIENT_BASE_URL = "http://127.0.0.1:3000"
const AXIOS_AUTH_CLIENT_BASE_URL_DOCKER = "http://localhost:80/auth"
const AXIOS_GAME_CLIENT_BASE_URL = "http://127.0.0.1:7777"
const AXIOS_GAME_CLIENT_BASE_URL_DOCKER = "http://localhost:80/backend"
export {
    DOCKER,
    AXIOS_AUTH_CLIENT_BASE_URL,
    AXIOS_AUTH_CLIENT_BASE_URL_DOCKER,
    AXIOS_GAME_CLIENT_BASE_URL,
    AXIOS_GAME_CLIENT_BASE_URL_DOCKER,
}
